// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzvuAgxw7u0hhGK0NmVvMBsQCyQZzJpqc',
    appId: '1:195737659353:web:460f04b9d572bf70349bc8',
    messagingSenderId: '195737659353',
    projectId: 'social-media-app-d781f',
    authDomain: 'social-media-app-d781f.firebaseapp.com',
    storageBucket: 'social-media-app-d781f.appspot.com',
    measurementId: 'G-ZE9M0RZ58F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCcEuNF0dqaRcPn04M5S5QisqZFnmhIf8',
    appId: '1:195737659353:android:6880ed6985ce1fd6349bc8',
    messagingSenderId: '195737659353',
    projectId: 'social-media-app-d781f',
    storageBucket: 'social-media-app-d781f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSuhba5HDJ4pJtv5G2R0AZUzkTfqoOmAM',
    appId: '1:195737659353:ios:76067c315502de3c349bc8',
    messagingSenderId: '195737659353',
    projectId: 'social-media-app-d781f',
    storageBucket: 'social-media-app-d781f.appspot.com',
    iosBundleId: 'com.dry.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSuhba5HDJ4pJtv5G2R0AZUzkTfqoOmAM',
    appId: '1:195737659353:ios:639e70b93cb3433d349bc8',
    messagingSenderId: '195737659353',
    projectId: 'social-media-app-d781f',
    storageBucket: 'social-media-app-d781f.appspot.com',
    iosBundleId: 'com.dry.social.RunnerTests',
  );
}
